import express from 'express';
import categoryRouter from './main-routes/CategoryRoutes.js';
import brandrouter from './main-routes/BrandRoutes.js';
import bannerRouter from './main-routes/BannerRoutes.js';
import productRouter from './main-routes/ProductRoutes.js';
const dashboardPrivateRouter = express.Router();
dashboardPrivateRouter.use('/categories', categoryRouter);
dashboardPrivateRouter.use('/brands', brandrouter);
dashboardPrivateRouter.use('/banners', bannerRouter);
dashboardPrivateRouter.use('/products',productRouter);
export default dashboardPrivateRouter;
